version: '3'
services:
  airflow:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:admin@postgresql:5432/airflow_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags/

  postgresql:
    platform: linux/x86_64
    image: postgres:15.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "covid_data"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: pg_isready -U postgres -d covid_data
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  minio:
    platform: linux/x86_64
    image: bitnami/minio:2024.5.1
    container_name: minio-container
    environment:
      - MINIO_ACCESS_KEY=minioaccesskey
      - MINIO_SECRET_KEY=miniosecretkey
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123456
      - MINIO_DEFAULT_BUCKETS=coviddata
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"

volumes:
  minio-data:
    driver: local
  postgres-data:
    driver: local