covid19:
  outputs:
    dev:
      dbname: covid_data
      host: postgresql
      pass: admin
      port: 5432
      schema: raw
      threads: 1
      type: postgres
      user: postgres
  target: dev
